org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=minenorth_map
mod_name=MineNorth Carte
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=fr.minenorth.map
mod_authors=Erwan
mod_description=Carte RP pour MineNorthRP : minicarte + carte plein ecran, sans affichage des joueurs, avec points de repere places par les OP.
